title : adp-multi
author :
  name : Maik Riechert
  github : neothemachine

navigation :
#  - archive.html
#  - tags.html
#  - categories.html
#  - pages.html
  - quick_start.md
  - MCFG.md
  - syntax.md
#  - architecture.md
#  - about.md
  
